version: '3.2'

services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - wp-files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: always
  wordpress:
    build: ./wordpress
    ports:
        - "9000:9000"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
        #MYSQL_ROOT_PASSWORD: 
      WORDPRESS_DB_NAME: ${DB_USER}
      WORDPRESS_DB_USER: ${DB_PASSWORD}
      WORDPRESS_DB_PASSWORD: ${DB_DATABASE}
    volumes:
      - wp-files:/var/www/html
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    restart: always
  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-files:/var/lib/mysql
    networks:
      - backend
    restart: always
networks:
  frontend:
  backend:
volumes:
  wp-files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ceddibao/data/wp-files'
  db-files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ceddibao/data/db-files'
